/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/j85KipvMPpe
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import DashboardContext from '@/context/DashboardContext'
import { Card, CardContent, CardHeader, CardTitle } from './ui/card'
import { useContext } from 'react'

/** Add fonts into your Next.js project:

import { Manrope } from 'next/font/google'
import { Rethink_Sans } from 'next/font/google'

manrope({
  subsets: ['latin'],
  display: 'swap',
})

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

export function Dashboard () {
  const { dataDashboard } = useContext(DashboardContext)
  return (
    <div className='grid min-h-screen w-full grid-cols-1 gap-6 p-6 md:grid-cols-2 md:p-10 lg:grid-cols-2 lg:gap-10 xl:grid-cols-2 xl:p-16'>
      <Card className='h-32 flex flex-col justify-between'>
        <div>
          <CardHeader>
            <CardTitle>Total Earnings</CardTitle>
          </CardHeader>
          <CardContent>
            <div className='text-5xl font-bold'>{
              dataDashboard.dineroRecolectado || '0'
              }
            </div>
          </CardContent>
        </div>
      </Card>
      <Card className='h-32 flex flex-col justify-between'>
        <div>
          <CardHeader>
            <CardTitle>Total People</CardTitle>
          </CardHeader>
          <CardContent>
            <div className='text-5xl font-bold'>{
              dataDashboard.cantidadPasajeros || '0'
              }
            </div>
          </CardContent>
        </div>
      </Card>
    </div>
  )
}
